# Generated by Django 4.2.6 on 2023-11-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_category_master'),
    ]

    operations = [
        migrations.CreateModel(
            name='book_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=50)),
                ('category_name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=500)),
                ('pic', models.CharField(max_length=500)),
                ('price', models.FloatField()),
                ('stock', models.IntegerField()),
                ('author', models.CharField(max_length=50)),
                ('keywords', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
    ]
