# Generated by Django 4.2.6 on 2023-12-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_book_master'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_master',
            name='author',
            field=models.CharField(max_length=30),
        ),
    ]
