# Generated by Django 4.2.6 on 2023-12-09 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_shopping_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='shopping_cart',
        ),
    ]
