# Generated by Django 4.2.6 on 2023-12-09 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_shopping_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopping_cart',
            name='pic',
        ),
    ]
