# Generated by Django 4.2.6 on 2023-12-09 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_shopping_cart_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopping_cart',
            name='book_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.book_master'),
        ),
        migrations.AlterField(
            model_name='shopping_cart',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.customer_details'),
        ),
    ]
