# Generated by Django 4.2.6 on 2023-12-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_shopping_cart_book_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopping_cart',
            name='book_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='shopping_cart',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
